name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Terraform Workspace (dev, prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
       

      - name: Terraform Init
        run: terraform init

      - name: Select/Create Workspace
        run: |
          terraform workspace list
          terraform workspace select "${{ github.event.inputs.environment }}" || terraform workspace new "${{ github.event.inputs.environment }}"

      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
       
