name: Terraform Destroy

# Trigger this workflow manually from GitHub UI
on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      # Checkout your Terraform code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      # Configure AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # adjust to match your setup

      # Initialize Terraform (loads backend state from S3)
      - name: Terraform Init
        run: terraform init

      # Destroy infrastructure
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
